# Generated by Django 4.2.1 on 2023-05-13 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(
                    primary_key=True, serialize=False)
                 ),
                ('title', models.CharField(
                    max_length=128, verbose_name='Titre')
                 ),
                ('description', models.CharField(max_length=2048)),
                ('type',
                 models.CharField(
                     choices=[('BACK-END', 'Back End'),
                              ('FRONT-END', 'Front End'),
                              ('iOS', 'Ios'),
                              ('ANDROID', 'Android')],
                     max_length=128)
                 ),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')
                 ),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(
                    blank=True,
                    max_length=2048, null=True)
                 ),
                ('tag', models.CharField(
                    choices=[
                        ('BUG', 'Bug'),
                        ('TASK', 'Task'),
                        ('IMPROVEMENT', 'Improvement')
                    ],
                    max_length=128)),
                ('priority', models.CharField(
                    choices=[
                        ('LOW', 'Low'),
                        ('MEDIUM', 'Medium'),
                        ('HIGH', 'High')
                    ],
                    max_length=128)),
                ('project_id', models.IntegerField()),
                ('status', models.CharField(
                    choices=[
                        ('T', 'To Do'),
                        ('IP', 'In Production'),
                        ('D', 'Done')
                    ],
                    max_length=128)),
                ('created_time', models.DateTimeField(
                    auto_now_add=True)),
                ('assignee_user_id', models.ForeignKey(
                    default=models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='issues',
                        to=settings.AUTH_USER_MODEL
                    ),
                    on_delete=django.db.models.deletion.SET_DEFAULT,
                    related_name='issues_assigned',
                    to=settings.AUTH_USER_MODEL)
                 ),
                ('author_user_id', models.ForeignKey(
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='issues',
                    to=settings.AUTH_USER_MODEL)),
                ('project_foreign_key', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='issues',
                    to='issuetrackingsystem.project')
                 ),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(
                    primary_key=True, serialize=False)),
                ('description', models.CharField(
                    max_length=2048)),
                ('created_time', models.DateTimeField(
                    auto_now_add=True)),
                ('author_user_id', models.ForeignKey(
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='comments',
                    to=settings.AUTH_USER_MODEL)
                 ),
                ('issue_id', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='comments',
                    to='issuetrackingsystem.issue')
                 ),
            ],
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')
                 ),
                ('user_id', models.IntegerField()),
                ('permission', models.CharField(
                    choices=[
                        ('CREATE_READ_UPDATE_DELETE', 'Crud'),
                        ('CREATE_READ', 'Cr')
                    ],
                    default='CREATE_READ',
                    max_length=50,
                    verbose_name='Permission')
                 ),
                ('role', models.CharField(
                    choices=[
                        ('CREATOR', 'Creator'),
                        ('CONTRIBUTOR', 'Contributor')
                    ],
                    default='CONTRIBUTOR',
                    max_length=128,
                    verbose_name='Rôle')
                 ),
                ('project_id', models.IntegerField()),
                ('project_foreign_key', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='contributors',
                    to='issuetrackingsystem.project')
                 ),
                ('user_foreign_key', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='contributors',
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='Utilisateurs')
                 ),
            ],
            options={
                'unique_together': {('user_id', 'project_id')},
            },
        ),
    ]
